class countryCodeConversion:
    nameCodeDict = {
        "Afghanistan": "AFG",
        "Aland Islands": "ALA",
        "Albania": "ALB",
        "Algeria": "DZA",
        "American Samoa": "ASM",
        "Andorra": "AND",
        "Angola": "AGO",
        "Anguilla": "AIA",
        "Antarctica": "ATA",
        "Antigua and Barbuda": "ATG",
        "Argentina": "ARG",
        "Armenia": "ARM",
        "Aruba": "ABW",
        "Australia": "AUS",
        "Austria": "AUT",
        "Azerbaijan": "AZE",
        "Bahamas": "BHS",
        "Bahrain": "BHR",
        "Bangladesh": "BGD",
        "Barbados": "BRB",
        "Belarus": "BLR",
        "Belgium": "BEL",
        "Belize": "BLZ",
        "Benin": "BEN",
        "Bermuda": "BMU",
        "Bhutan": "BTN",
        "Bolivia (Plurinational State of)": "BOL",
        "Bonaire, Sint Eustatius and Saba": "BES",
        "Bosnia and Herzegovina": "BIH",
        "Botswana": "BWA",
        "Bouvet Island": "BVT",
        "Brazil": "BRA",
        "British Indian Ocean Territory": "IOT",
        "British Virgin Islands": "VGB",
        "Brunei Darussalam": "BRN",
        "Bulgaria": "BGR",
        "Burkina Faso": "BFA",
        "Burundi": "BDI",
        "Cabo Verde": "CPV",
        "Cambodia": "KHM",
        "Cameroon": "CMR",
        "Canada": "CAN",
        "Cayman Islands": "CYM",
        "Central African Republic": "CAF",
        "Chad": "TCD",
        "Chile": "CHL",
        "China": "CHN",
        "China, Hong Kong Special Administrative Region": "HKG",
        "China, Macao Special Administrative Region": "MAC",
        "Christmas Island": "CXR",
        "Cocos (Keeling) Islands": "CCK",
        "Colombia": "COL",
        "Comoros": "COM",
        "Congo": "COG",
        "Cook Islands": "COK",
        "Costa Rica": "CRI",
        "Cote d'Ivoire": "CIV",
        "Croatia": "HRV",
        "Cuba": "CUB",
        "Curacao": "CUW",
        "Cyprus": "CYP",
        "Czechia": "CZE",
        "Democratic People's Republic of Korea": "PRK",
        "Congo, the Democratic Republic of the": "COD",
        "Denmark": "DNK",
        "Djibouti": "DJI",
        "Dominica": "DMA",
        "Dominican Republic": "DOM",
        "Ecuador": "ECU",
        "Egypt": "EGY",
        "El Salvador": "SLV",
        "Equatorial Guinea": "GNQ",
        "Eritrea": "ERI",
        "Estonia": "EST",
        "Eswatini": "SWZ",
        "Ethiopia": "ETH",
        "Falkland Islands (Malvinas)": "FLK",
        "Faroe Islands": "FRO",
        "Fiji": "FJI",
        "Finland": "FIN",
        "France": "FRA",
        "French Guiana": "GUF",
        "French Polynesia": "PYF",
        "French Southern Territories": "ATF",
        "Gabon": "GAB",
        "Gambia": "GMB",
        "Georgia": "GEO",
        "Germany": "DEU",
        "Ghana": "GHA",
        "Gibraltar": "GIB",
        "Greece": "GRC",
        "Greenland": "GRL",
        "Grenada": "GRD",
        "Guadeloupe": "GLP",
        "Guam": "GUM",
        "Guatemala": "GTM",
        "Guernsey": "GGY",
        "Guinea": "GIN",
        "Guinea-Bissau": "GNB",
        "Guyana": "GUY",
        "Haiti": "HTI",
        "Heard Island and McDonald Islands": "HMD",
        "Holy See": "VAT",
        "Honduras": "HND",
        "Hungary": "HUN",
        "Iceland": "ISL",
        "India": "IND",
        "Indonesia": "IDN",
        "Iran (Islamic Republic of)": "IRN",
        "Iraq": "IRQ",
        "Ireland": "IRL",
        "Isle of Man": "IMN",
        "Israel": "ISR",
        "Italy": "ITA",
        "Jamaica": "JAM",
        "Japan": "JPN",
        "Jersey": "JEY",
        "Jordan": "JOR",
        "Kazakhstan": "KAZ",
        "Kenya": "KEN",
        "Kiribati": "KIR",
        "Kuwait": "KWT",
        "Kyrgyzstan": "KGZ",
        "Lao People's Democratic Republic": "LAO",
        "Latvia": "LVA",
        "Lebanon": "LBN",
        "Lesotho": "LSO",
        "Liberia": "LBR",
        "Libya": "LBY",
        "Liechtenstein": "LIE",
        "Lithuania": "LTU",
        "Luxembourg": "LUX",
        "Madagascar": "MDG",
        "Malawi": "MWI",
        "Malaysia": "MYS",
        "Maldives": "MDV",
        "Mali": "MLI",
        "Malta": "MLT",
        "Marshall Islands": "MHL",
        "Martinique": "MTQ",
        "Mauritania": "MRT",
        "Mauritius": "MUS",
        "Mayotte": "MYT",
        "Mexico": "MEX",
        "Micronesia (Federated States of)": "FSM",
        "Monaco": "MCO",
        "Mongolia": "MNG",
        "Montenegro": "MNE",
        "Montserrat": "MSR",
        "Morocco": "MAR",
        "Mozambique": "MOZ",
        "Myanmar": "MMR",
        "Namibia": "NAM",
        "Nauru": "NRU",
        "Nepal": "NPL",
        "Netherlands": "NLD",
        "New Caledonia": "NCL",
        "New Zealand": "NZL",
        "Nicaragua": "NIC",
        "Niger": "NER",
        "Nigeria": "NGA",
        "Niue": "NIU",
        "Norfolk Island": "NFK",
        "North Macedonia": "MKD",
        "Northern Mariana Islands": "MNP",
        "Norway": "NOR",
        "Oman": "OMN",
        "Pakistan": "PAK",
        "Palau": "PLW",
        "Panama": "PAN",
        "Papua New Guinea": "PNG",
        "Paraguay": "PRY",
        "Peru": "PER",
        "Philippines": "PHL",
        "Pitcairn": "PCN",
        "Poland": "POL",
        "Portugal": "PRT",
        "Puerto Rico": "PRI",
        "Qatar": "QAT",
        "Republic of Korea": "KOR",
        "Republic of Moldova": "MDA",
        "Reunion": "REU",
        "Romania": "ROU",
        "Russian Federation": "RUS",
        "Rwanda": "RWA",
        "Saint Barthelemy": "BLM",
        "Saint Helena": "SHN",
        "Saint Kitts and Nevis": "KNA",
        "Saint Lucia": "LCA",
        "Saint Martin (French Part)": "MAF",
        "Saint Pierre and Miquelon": "SPM",
        "Saint Vincent and the Grenadines": "VCT",
        "Samoa": "WSM",
        "San Marino": "SMR",
        "Sao Tome and Principe": "STP",
        "Saudi Arabia": "SAU",
        "Senegal": "SEN",
        "Serbia": "SRB",
        "Seychelles": "SYC",
        "Sierra Leone": "SLE",
        "Singapore": "SGP",
        "Sint Maarten (Dutch part)": "SXM",
        "Slovakia": "SVK",
        "Slovenia": "SVN",
        "Solomon Islands": "SLB",
        "Somalia": "SOM",
        "South Africa": "ZAF",
        "South Georgia and the South Sandwich Islands": "SGS",
        "South Sudan": "SSD",
        "Spain": "ESP",
        "Sri Lanka": "LKA",
        "State of Palestine": "PSE",
        "Sudan": "SDN",
        "Suriname": "SUR",
        "Svalbard and Jan Mayen Islands": "SJM",
        "Sweden": "SWE",
        "Switzerland": "CHE",
        "Syrian Arab Republic": "SYR",
        "Tajikistan": "TJK",
        "Thailand": "THA",
        "Timor-Leste": "TLS",
        "Togo": "TGO",
        "Tokelau": "TKL",
        "Tonga": "TON",
        "Trinidad and Tobago": "TTO",
        "Tunisia": "TUN",
        "Turkey": "TUR",
        "Turkmenistan": "TKM",
        "Turks and Caicos Islands": "TCA",
        "Tuvalu": "TUV",
        "Uganda": "UGA",
        "Ukraine": "UKR",
        "United Arab Emirates": "ARE",
        "United Kingdom of Great Britain and Northern Ireland": "GBR",
        "United Republic of Tanzania": "TZA",
        "United States Minor Outlying Islands": "UMI",
        "United States of America": "USA",
        "United States Virgin Islands": "VIR",
        "Uruguay": "URY",
        "Uzbekistan": "UZB",
        "Vanuatu": "VUT",
        "Venezuela (Bolivarian Republic of)": "VEN",
        "Viet Nam": "VNM",
        "Wallis and Futuna Islands": "WLF",
        "Western Sahara": "ESH",
        "Yemen": "YEM",
        "Zambia": "ZMB",
        "Zimbabwe": "ZWE"
    }

    codeNameDict = {
        "AFG": "Afghanistan",
        "ALA": "Aland Islands",
        "ALB": "Albania",
        "DZA": "Algeria",
        "ASM": "American Samoa",
        "AND": "Andorra",
        "AGO": "Angola",
        "AIA": "Anguilla",
        "ATA": "Antarctica",
        "ATG": "Antigua and Barbuda",
        "ARG": "Argentina",
        "ARM": "Armenia",
        "ABW": "Aruba",
        "AUS": "Australia",
        "AUT": "Austria",
        "AZE": "Azerbaijan",
        "BHS": "Bahamas",
        "BHR": "Bahrain",
        "BGD": "Bangladesh",
        "BRB": "Barbados",
        "BLR": "Belarus",
        "BEL": "Belgium",
        "BLZ": "Belize",
        "BEN": "Benin",
        "BMU": "Bermuda",
        "BTN": "Bhutan",
        "BOL": "Bolivia (Plurinational State of)",
        "BES": "Bonaire, Sint Eustatius and Saba",
        "BIH": "Bosnia and Herzegovina",
        "BWA": "Botswana",
        "BVT": "Bouvet Island",
        "BRA": "Brazil",
        "IOT": "British Indian Ocean Territory",
        "VGB": "British Virgin Islands",
        "BRN": "Brunei Darussalam",
        "BGR": "Bulgaria",
        "BFA": "Burkina Faso",
        "BDI": "Burundi",
        "CPV": "Cabo Verde",
        "KHM": "Cambodia",
        "CMR": "Cameroon",
        "CAN": "Canada",
        "CYM": "Cayman Islands",
        "CAF": "Central African Republic",
        "TCD": "Chad",
        "CHL": "Chile",
        "CHN": "China",
        "HKG": "China, Hong Kong Special Administrative Region",
        "MAC": "China, Macao Special Administrative Region",
        "CXR": "Christmas Island",
        "CCK": "Cocos (Keeling) Islands",
        "COL": "Colombia",
        "COM": "Comoros",
        "COG": "Congo",
        "COK": "Cook Islands",
        "CRI": "Costa Rica",
        "CIV": "Cote d'Ivoire",
        "HRV": "Croatia",
        "CUB": "Cuba",
        "CUW": "Curacao",
        "CYP": "Cyprus",
        "CZE": "Czechia",
        "PRK": "Democratic People's Republic of Korea",
        "COD": "Democratic Republic of the Congo",
        "DNK": "Denmark",
        "DJI": "Djibouti",
        "DMA": "Dominica",
        "DOM": "Dominican Republic",
        "ECU": "Ecuador",
        "EGY": "Egypt",
        "SLV": "El Salvador",
        "GNQ": "Equatorial Guinea",
        "ERI": "Eritrea",
        "EST": "Estonia",
        "SWZ": "Eswatini",
        "ETH": "Ethiopia",
        "FLK": "Falkland Islands (Malvinas)",
        "FRO": "Faroe Islands",
        "FJI": "Fiji",
        "FIN": "Finland",
        "FRA": "France",
        "GUF": "French Guiana",
        "PYF": "French Polynesia",
        "ATF": "French Southern Territories",
        "GAB": "Gabon",
        "GMB": "Gambia",
        "GEO": "Georgia",
        "DEU": "Germany",
        "GHA": "Ghana",
        "GIB": "Gibraltar",
        "GRC": "Greece",
        "GRL": "Greenland",
        "GRD": "Grenada",
        "GLP": "Guadeloupe",
        "GUM": "Guam",
        "GTM": "Guatemala",
        "GGY": "Guernsey",
        "GIN": "Guinea",
        "GNB": "Guinea-Bissau",
        "GUY": "Guyana",
        "HTI": "Haiti",
        "HMD": "Heard Island and McDonald Islands",
        "VAT": "Holy See",
        "HND": "Honduras",
        "HUN": "Hungary",
        "ISL": "Iceland",
        "IND": "India",
        "IDN": "Indonesia",
        "IRN": "Iran (Islamic Republic of)",
        "IRQ": "Iraq",
        "IRL": "Ireland",
        "IMN": "Isle of Man",
        "ISR": "Israel",
        "ITA": "Italy",
        "JAM": "Jamaica",
        "JPN": "Japan",
        "JEY": "Jersey",
        "JOR": "Jordan",
        "KAZ": "Kazakhstan",
        "KEN": "Kenya",
        "KIR": "Kiribati",
        "KWT": "Kuwait",
        "KGZ": "Kyrgyzstan",
        "LAO": "Lao People's Democratic Republic",
        "LVA": "Latvia",
        "LBN": "Lebanon",
        "LSO": "Lesotho",
        "LBR": "Liberia",
        "LBY": "Libya",
        "LIE": "Liechtenstein",
        "LTU": "Lithuania",
        "LUX": "Luxembourg",
        "MDG": "Madagascar",
        "MWI": "Malawi",
        "MYS": "Malaysia",
        "MDV": "Maldives",
        "MLI": "Mali",
        "MLT": "Malta",
        "MHL": "Marshall Islands",
        "MTQ": "Martinique",
        "MRT": "Mauritania",
        "MUS": "Mauritius",
        "MYT": "Mayotte",
        "MEX": "Mexico",
        "FSM": "Micronesia (Federated States of)",
        "MCO": "Monaco",
        "MNG": "Mongolia",
        "MNE": "Montenegro",
        "MSR": "Montserrat",
        "MAR": "Morocco",
        "MOZ": "Mozambique",
        "MMR": "Myanmar",
        "NAM": "Namibia",
        "NRU": "Nauru",
        "NPL": "Nepal",
        "NLD": "Netherlands",
        "NCL": "New Caledonia",
        "NZL": "New Zealand",
        "NIC": "Nicaragua",
        "NER": "Niger",
        "NGA": "Nigeria",
        "NIU": "Niue",
        "NFK": "Norfolk Island",
        "MKD": "North Macedonia",
        "MNP": "Northern Mariana Islands",
        "NOR": "Norway",
        "OMN": "Oman",
        "PAK": "Pakistan",
        "PLW": "Palau",
        "PAN": "Panama",
        "PNG": "Papua New Guinea",
        "PRY": "Paraguay",
        "PER": "Peru",
        "PHL": "Philippines",
        "PCN": "Pitcairn",
        "POL": "Poland",
        "PRT": "Portugal",
        "PRI": "Puerto Rico",
        "QAT": "Qatar",
        "KOR": "Republic of Korea",
        "MDA": "Republic of Moldova",
        "REU": "Reunion",
        "ROU": "Romania",
        "RUS": "Russian Federation",
        "RWA": "Rwanda",
        "BLM": "Saint Barthelemy",
        "SHN": "Saint Helena",
        "KNA": "Saint Kitts and Nevis",
        "LCA": "Saint Lucia",
        "MAF": "Saint Martin (French Part)",
        "SPM": "Saint Pierre and Miquelon",
        "VCT": "Saint Vincent and the Grenadines",
        "WSM": "Samoa",
        "SMR": "San Marino",
        "STP": "Sao Tome and Principe",
        "SAU": "Saudi Arabia",
        "SEN": "Senegal",
        "SRB": "Serbia",
        "SYC": "Seychelles",
        "SLE": "Sierra Leone",
        "SGP": "Singapore",
        "SXM": "Sint Maarten (Dutch part)",
        "SVK": "Slovakia",
        "SVN": "Slovenia",
        "SLB": "Solomon Islands",
        "SOM": "Somalia",
        "ZAF": "South Africa",
        "SGS": "South Georgia and the South Sandwich Islands",
        "SSD": "South Sudan",
        "ESP": "Spain",
        "LKA": "Sri Lanka",
        "PSE": "State of Palestine",
        "SDN": "Sudan",
        "SUR": "Suriname",
        "SJM": "Svalbard and Jan Mayen Islands",
        "SWE": "Sweden",
        "CHE": "Switzerland",
        "SYR": "Syrian Arab Republic",
        "TJK": "Tajikistan",
        "THA": "Thailand",
        "TLS": "Timor-Leste",
        "TGO": "Togo",
        "TKL": "Tokelau",
        "TON": "Tonga",
        "TTO": "Trinidad and Tobago",
        "TUN": "Tunisia",
        "TUR": "Turkey",
        "TKM": "Turkmenistan",
        "TCA": "Turks and Caicos Islands",
        "TUV": "Tuvalu",
        "UGA": "Uganda",
        "UKR": "Ukraine",
        "ARE": "United Arab Emirates",
        "GBR": "United Kingdom of Great Britain and Northern Ireland",
        "TZA": "United Republic of Tanzania",
        "UMI": "United States Minor Outlying Islands",
        "USA": "United States of America",
        "VIR": "United States Virgin Islands",
        "URY": "Uruguay",
        "UZB": "Uzbekistan",
        "VUT": "Vanuatu",
        "VEN": "Venezuela (Bolivarian Republic of)",
        "VNM": "Viet Nam",
        "WLF": "Wallis and Futuna Islands",
        "ESH": "Western Sahara",
        "YEM": "Yemen",
        "ZMB": "Zambia",
        "ZWE": "Zimbabwe"
    }

    fipsNameToCodeDict = {
        "Afghanistan": "AF",
        "Albania": "AL",
        "Algeria": "AG",
        "American Samoa": "AQ",
        "Andorra": "AN",
        "Angola": "AO",
        "Anguilla": "AV",
        "Antarctica": "AY",
        "Antigua and Barbuda": "AC",
        "Argentina": "AR",
        "Armenia": "AM",
        "Aruba": "AA",
        "Australia": "AS",
        "Austria": "AU",
        "Azerbaijan": "AJ",
        "Bahamas": "BF",
        "Bahrain": "BA",
        "Bangladesh": "BG",
        "Barbados": "BB",
        "Belarus": "BO",
        "Belgium": "BE",
        "Belize": "BH",
        "Benin": "BN",
        "Bermuda": "BD",
        "Bhutan": "BT",
        "Bolivia, Plurinational State Of": "BL",
        "Bosnia and Herzegovina": "BK",
        "Botswana": "BC",
        "Bouvet Island": "BV",
        "Brazil": "BR",
        "British Indian Ocean Territory": "IO",
        "Brunei Darussalam": "BX",
        "Bulgaria": "BU",
        "Burkina Faso": "UV",
        "Burundi": "BY",
        "Cabo Verde": "CV",
        "Cambodia": "CB",
        "Cameroon": "CM",
        "Canada": "CA",
        "Cayman Islands": "CJ",
        "Central African Republic": "CT",
        "Chad": "CD",
        "Chile": "CI",
        "China": "CH",
        "Christmas Island": "KT",
        "Cocos (Keeling) Islands": "CK",
        "Colombia": "CO",
        "Comoros": "CN",
        "Congo": "CF",
        "Congo, the Democratic Republic of the": "CG",
        "Cook Islands": "CW",
        "Costa Rica": "CS",
        "Cote d’Ivoire": "IV",
        "Croatia": "HR",
        "Cuba": "CU",
        "Curacao": "UC",
        "Cyprus": "CY",
        "Czechia": "EZ",
        "Denmark": "DK",
        "Djibouti": "DJ",
        "Dominica": "DO",
        "Dominican Republic": "DR",
        "Ecuador": "EC",
        "Egypt": "EG",
        "El Salvador": "ES",
        "Equatorial Guinea": "EK",
        "Eritrea": "ER",
        "Estonia": "EN",
        "Eswatini": "WZ",
        "Ethiopia": "ET",
        "Falkland Islands (Malvinas)": "FK",
        "Faroe Islands": "FO",
        "Fiji": "FJ",
        "Finland": "FI",
        "France": "FR",
        "French Guiana": "FG",
        "French Polynesia": "FP",
        "French Southern Territories": "FS",
        "Gabon": "GB",
        "Gambia": "GA",
        "Georgia": "GG",
        "Germany": "GM",
        "Ghana": "GH",
        "Gibraltar": "GI",
        "Greece": "GR",
        "Greenland": "GL",
        "Grenada": "GJ",
        "Guadeloupe": "GP",
        "Guam": "GQ",
        "Guatemala": "GT",
        "Guernsey": "GK",
        "Guinea": "GV",
        "Guinea-Bissau": "PU",
        "Guyana": "GY",
        "Haiti": "HA",
        "Heard Island and McDonald Islands": "HM",
        "Holy See": "VT",
        "Honduras": "HO",
        "Hong Kong": "HK",
        "Hungary": "HU",
        "Iceland": "IC",
        "India": "IN",
        "Indonesia": "ID",
        "Iran, Islamic Republic of": "IR",
        "Iraq": "IZ",
        "Ireland": "EI",
        "Isle of Man": "IM",
        "Israel": "IS",
        "Italy": "IT",
        "Jamaica": "JM",
        "Japan": "JA",
        "Jersey": "JE",
        "Jordan": "JO",
        "Kazakhstan": "KZ",
        "Kenya": "KE",
        "Kiribati": "KR",
        "Korea, Democratic People’s Republic of": "KN",
        "Korea, Republic of": "KS",
        "Kuwait": "KU",
        "Kyrgyzstan": "KG",
        "Lao People’s Democratic Republic": "LA",
        "Latvia": "LG",
        "Lebanon": "LE",
        "Lesotho": "LT",
        "Liberia": "LI",
        "Libya": "LY",
        "Liechtenstein": "LS",
        "Lithuania": "LH",
        "Luxembourg": "LU",
        "Macao": "MC",
        "Macedonia, the former Yugoslav Republic of": "MK",
        "Madagascar": "MA",
        "Malawi": "MI",
        "Malaysia": "MY",
        "Maldives": "MV",
        "Mali": "ML",
        "Malta": "MT",
        "Marshall Islands": "RM",
        "Martinique": "MB",
        "Mauritania": "MR",
        "Mauritius": "MP",
        "Mayotte": "MF",
        "Mexico": "MX",
        "Micronesia, Federated States of": "FM",
        "Moldova, Republic of": "MD",
        "Monaco": "MN",
        "Mongolia": "MG",
        "Montenegro": "MJ",
        "Montserrat": "MH",
        "Morocco": "MO",
        "Mozambique": "MZ",
        "Myanmar": "BM",
        "Namibia": "WA",
        "Nauru": "NR",
        "Nepal": "NP",
        "Netherlands": "NL",
        "New Caledonia": "NC",
        "New Zealand": "NZ",
        "Nicaragua": "NU",
        "Niger": "NG",
        "Nigeria": "NI",
        "Niue": "NE",
        "Norfolk Island": "NF",
        "Northern Mariana Islands": "CQ",
        "Norway": "NO",
        "Oman": "MU",
        "Pakistan": "PK",
        "Palau": "PS",
        "Palestine, State of": "WE",
        "Panama": "PM",
        "Papua New Guinea": "PP",
        "Paraguay": "PA",
        "Peru": "PE",
        "Philippines": "RP",
        "Pitcairn": "PC",
        "Poland": "PL",
        "Portugal": "PO",
        "Puerto Rico": "RQ",
        "Qatar": "QA",
        "Reunion": "RE",
        "Romania": "RO",
        "Russian Federation": "RS",
        "Rwanda": "RW",
        "Saint Barthelemy": "TB",
        "Saint Helena, Ascension and Tristan da Cunha": "SH",
        "Saint Kitts and Nevis": "SC",
        "Saint Lucia": "ST",
        "Saint Martin": "RN",
        "Saint Pierre and Miquelon": "SB",
        "Saint Vincent and the Grenadines": "VC",
        "Samoa": "WS",
        "San Marino": "SM",
        "Sao Tome and Principe": "TP",
        "Saudi Arabia": "SA",
        "Senegal": "SG",
        "Serbia": "RI",
        "Seychelles": "SE",
        "Sierra Leone": "SL",
        "Singapore": "SN",
        "Sint Maarten": "NN",
        "Slovakia": "LO",
        "Slovenia": "SI",
        "Solomon Islands": "BP",
        "Somalia": "SO",
        "South Africa": "SF",
        "South Georgia and the South Sandwich Islands": "SX",
        "South Sudan": "OD",
        "Spain": "SP",
        "Sri Lanka": "CE",
        "Sudan": "SU",
        "Suriname": "NS",
        "Svalbard and Jan Mayen": "SV",
        "Swaziland": "WZ",
        "Sweden": "SW",
        "Switzerland": "SZ",
        "Syrian Arab Republic": "SY",
        "Taiwan": "TW",
        "Tajikistan": "TI",
        "United Republic of Tanzania": "TZ",
        "Thailand": "TH",
        "Timor-Leste": "TT",
        "Togo": "TO",
        "Tokelau": "TL",
        "Tonga": "TN",
        "Trinidad and Tobago": "TD",
        "Tunisia": "TS",
        "Turkey": "TU",
        "Turkmenistan": "TX",
        "Turks and Caicos Islands": "TK",
        "Tuvalu": "TV",
        "Uganda": "UG",
        "Ukraine": "UA",
        "United Arab Emirates": "AE",
        "United Kingdom": "UK",
        "United States": "US",
        "Uruguay": "UY",
        "Uzbekistan": "UZ",
        "Vanuatu": "NH",
        "Venezuela, Bolivarian Republic of": "VE",
        "Viet Nam": "VN",
        "Virgin Islands, British": "VI",
        "Virgin Islands, U.S.": "VQ",
        "Wallis and Futuna": "WF",
        "Western Sahara": "WI",
        "Yemen": "YM",
        "Zambia": "ZA",
        "Zimbabwe": "ZI"
    }

    fipsCodeToNameDict = {
        "AF": "Afghanistan",
        "AL": "Albania",
        "AG": "Algeria",
        "AQ": "American Samoa",
        "AN": "Andorra",
        "AO": "Angola",
        "AV": "Anguilla",
        "AY": "Antarctica",
        "AC": "Antigua and Barbuda",
        "AR": "Argentina",
        "AM": "Armenia",
        "AA": "Aruba",
        "AS": "Australia",
        "AU": "Austria",
        "AJ": "Azerbaijan",
        "BF": "Bahamas",
        "BA": "Bahrain",
        "BG": "Bangladesh",
        "BB": "Barbados",
        "BO": "Belarus",
        "BE": "Belgium",
        "BH": "Belize",
        "BN": "Benin",
        "BD": "Bermuda",
        "BT": "Bhutan",
        "BL": "Bolivia, Plurinational State Of",
        "BK": "Bosnia and Herzegovina",
        "BC": "Botswana",
        "BV": "Bouvet Island",
        "BR": "Brazil",
        "IO": "British Indian Ocean Territory",
        "BX": "Brunei Darussalam",
        "BU": "Bulgaria",
        "UV": "Burkina Faso",
        "BY": "Burundi",
        "CV": "Cabo Verde",
        "CB": "Cambodia",
        "CM": "Cameroon",
        "CA": "Canada",
        "CJ": "Cayman Islands",
        "CT": "Central African Republic",
        "CD": "Chad",
        "CI": "Chile",
        "CH": "China",
        "KT": "Christmas Island",
        "CK": "Cocos (Keeling) Islands",
        "CO": "Colombia",
        "CN": "Comoros",
        "CF": "Congo",
        "CG": "Congo, the Democratic Republic of the",
        "CW": "Cook Islands",
        "CS": "Costa Rica",
        "IV": "Cote d’Ivoire",
        "HR": "Croatia",
        "CU": "Cuba",
        "UC": "Curacao",
        "CY": "Cyprus",
        "EZ": "Czechia",
        "DK": "Denmark",
        "DJ": "Djibouti",
        "DO": "Dominica",
        "DR": "Dominican Republic",
        "EC": "Ecuador",
        "EG": "Egypt",
        "ES": "El Salvador",
        "EK": "Equatorial Guinea",
        "ER": "Eritrea",
        "EN": "Estonia",
        "ET": "Ethiopia",
        "FK": "Falkland Islands (Malvinas)",
        "FO": "Faroe Islands",
        "FJ": "Fiji",
        "FI": "Finland",
        "FR": "France",
        "FG": "French Guiana",
        "FP": "French Polynesia",
        "FS": "French Southern Territories",
        "GB": "Gabon",
        "GA": "Gambia",
        "GG": "Georgia",
        "GM": "Germany",
        "GH": "Ghana",
        "GI": "Gibraltar",
        "GR": "Greece",
        "GL": "Greenland",
        "GJ": "Grenada",
        "GP": "Guadeloupe",
        "GQ": "Guam",
        "GT": "Guatemala",
        "GK": "Guernsey",
        "GV": "Guinea",
        "PU": "Guinea-Bissau",
        "GY": "Guyana",
        "HA": "Haiti",
        "HM": "Heard Island and McDonald Islands",
        "VT": "Holy See",
        "HO": "Honduras",
        "HK": "Hong Kong",
        "HU": "Hungary",
        "IC": "Iceland",
        "IN": "India",
        "ID": "Indonesia",
        "IR": "Iran, Islamic Republic of",
        "IZ": "Iraq",
        "EI": "Ireland",
        "IM": "Isle of Man",
        "IS": "Israel",
        "IT": "Italy",
        "JM": "Jamaica",
        "JA": "Japan",
        "JE": "Jersey",
        "JO": "Jordan",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "KR": "Kiribati",
        "KN": "Korea, Democratic People’s Republic of",
        "KS": "Korea, Republic of",
        "KU": "Kuwait",
        "KG": "Kyrgyzstan",
        "LA": "Lao People’s Democratic Republic",
        "LG": "Latvia",
        "LE": "Lebanon",
        "LT": "Lesotho",
        "LI": "Liberia",
        "LY": "Libya",
        "LS": "Liechtenstein",
        "LH": "Lithuania",
        "LU": "Luxembourg",
        "MC": "Macao",
        "MK": "Macedonia, the former Yugoslav Republic of",
        "MA": "Madagascar",
        "MI": "Malawi",
        "MY": "Malaysia",
        "MV": "Maldives",
        "ML": "Mali",
        "MT": "Malta",
        "RM": "Marshall Islands",
        "MB": "Martinique",
        "MR": "Mauritania",
        "MP": "Mauritius",
        "MF": "Mayotte",
        "MX": "Mexico",
        "FM": "Micronesia, Federated States of",
        "MD": "Moldova, Republic of",
        "MN": "Monaco",
        "MG": "Mongolia",
        "MJ": "Montenegro",
        "MH": "Montserrat",
        "MO": "Morocco",
        "MZ": "Mozambique",
        "BM": "Myanmar",
        "WA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NL": "Netherlands",
        "NC": "New Caledonia",
        "NZ": "New Zealand",
        "NU": "Nicaragua",
        "NG": "Niger",
        "NI": "Nigeria",
        "NE": "Niue",
        "NF": "Norfolk Island",
        "CQ": "Northern Mariana Islands",
        "NO": "Norway",
        "MU": "Oman",
        "PK": "Pakistan",
        "PS": "Palau",
        "WE": "Palestine, State of",
        "PM": "Panama",
        "PP": "Papua New Guinea",
        "PA": "Paraguay",
        "PE": "Peru",
        "RP": "Philippines",
        "PC": "Pitcairn",
        "PL": "Poland",
        "PO": "Portugal",
        "RQ": "Puerto Rico",
        "QA": "Qatar",
        "RE": "Reunion",
        "RO": "Romania",
        "RS": "Russian Federation",
        "RW": "Rwanda",
        "TB": "Saint Barthelemy",
        "SH": "Saint Helena, Ascension and Tristan da Cunha",
        "SC": "Saint Kitts and Nevis",
        "ST": "Saint Lucia",
        "RN": "Saint Martin",
        "SB": "Saint Pierre and Miquelon",
        "VC": "Saint Vincent and the Grenadines",
        "WS": "Samoa",
        "SM": "San Marino",
        "TP": "Sao Tome and Principe",
        "SA": "Saudi Arabia",
        "SG": "Senegal",
        "RI": "Serbia",
        "SE": "Seychelles",
        "SL": "Sierra Leone",
        "SN": "Singapore",
        "NN": "Sint Maarten",
        "LO": "Slovakia",
        "SI": "Slovenia",
        "BP": "Solomon Islands",
        "SO": "Somalia",
        "SF": "South Africa",
        "SX": "South Georgia and the South Sandwich Islands",
        "OD": "South Sudan",
        "SP": "Spain",
        "CE": "Sri Lanka",
        "SU": "Sudan",
        "NS": "Suriname",
        "SV": "Svalbard and Jan Mayen",
        "WZ": "Swaziland",
        "SW": "Sweden",
        "SZ": "Switzerland",
        "SY": "Syrian Arab Republic",
        "TW": "Taiwan",
        "TI": "Tajikistan",
        "TZ": "Tanzania, United Republic of",
        "TH": "Thailand",
        "TT": "Timor-Leste",
        "TO": "Togo",
        "TL": "Tokelau",
        "TN": "Tonga",
        "TD": "Trinidad and Tobago",
        "TS": "Tunisia",
        "TU": "Turkey",
        "TX": "Turkmenistan",
        "TK": "Turks and Caicos Islands",
        "TV": "Tuvalu",
        "UG": "Uganda",
        "UA": "Ukraine",
        "AE": "United Arab Emirates",
        "UK": "United Kingdom",
        "US": "United States",
        "UY": "Uruguay",
        "UZ": "Uzbekistan",
        "NH": "Vanuatu",
        "VE": "Venezuela, Bolivarian Republic of",
        "VN": "Viet Nam",
        "VI": "Virgin Islands, British",
        "VQ": "Virgin Islands, U.S.",
        "WF": "Wallis and Futuna",
        "WI": "Western Sahara",
        "YM": "Yemen",
        "ZA": "Zambia",
        "ZI": "Zimbabwe"
    }

    def codeToName(self, code):
        try:
            return self.codeNameDict[code]
        except:
            return 1

    def nameToCode(self, name):
        try:
            return self.nameCodeDict[name]
        except:
            return 1

    def fipsCodeToName(self, code):
        try:
            return self.fipsCodeToNameDict[code]
        except:
            return 1

    def fipsNameToCode(self, code):
        try:
            return self.fipsNameToCodeDict[code]
        except:
            return 1
